import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Nav from '@/layout/nav'
import Header from '@/layout/header'
import Main from '@/layout/main'
import Footer from '@/layout/footer'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <Nav></Nav>
        <Main>
          {children}
        </Main>
        <Footer></Footer>
      </body>
    </html>
  )
}
